"""add wallet tables

Revision ID: 04bd492c090d
Revises: 7545cf816a9c
Create Date: 2025-11-25 19:24:32.066108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bd492c090d'
down_revision: Union[str, Sequence[str], None] = '7545cf816a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('meta_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_accounts_user_id'), 'wallet_accounts', ['user_id'], unique=False)
    op.create_table('wallet_balances',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('available_cents', sa.Integer(), nullable=False),
    sa.Column('pending_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wallet_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('wallet_deposits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('mpesa_reference', sa.String(length=64), nullable=True),
    sa.Column('mpesa_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wallet_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_deposits_account_id'), 'wallet_deposits', ['account_id'], unique=False)
    op.create_index(op.f('ix_wallet_deposits_user_id'), 'wallet_deposits', ['user_id'], unique=False)
    op.create_table('wallet_ledger_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('debit_account_id', sa.String(length=36), nullable=False),
    sa.Column('credit_account_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('reference_type', sa.String(length=32), nullable=True),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['credit_account_id'], ['wallet_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['debit_account_id'], ['wallet_accounts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_ledger_entries_credit_account_id'), 'wallet_ledger_entries', ['credit_account_id'], unique=False)
    op.create_index(op.f('ix_wallet_ledger_entries_debit_account_id'), 'wallet_ledger_entries', ['debit_account_id'], unique=False)
    op.create_table('wallet_withdrawals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('mpesa_phone', sa.String(length=20), nullable=True),
    sa.Column('mpesa_reference', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['wallet_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_withdrawals_account_id'), 'wallet_withdrawals', ['account_id'], unique=False)
    op.create_index(op.f('ix_wallet_withdrawals_user_id'), 'wallet_withdrawals', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_withdrawals_user_id'), table_name='wallet_withdrawals')
    op.drop_index(op.f('ix_wallet_withdrawals_account_id'), table_name='wallet_withdrawals')
    op.drop_table('wallet_withdrawals')
    op.drop_index(op.f('ix_wallet_ledger_entries_debit_account_id'), table_name='wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_ledger_entries_credit_account_id'), table_name='wallet_ledger_entries')
    op.drop_table('wallet_ledger_entries')
    op.drop_index(op.f('ix_wallet_deposits_user_id'), table_name='wallet_deposits')
    op.drop_index(op.f('ix_wallet_deposits_account_id'), table_name='wallet_deposits')
    op.drop_table('wallet_deposits')
    op.drop_table('wallet_balances')
    op.drop_index(op.f('ix_wallet_accounts_user_id'), table_name='wallet_accounts')
    op.drop_table('wallet_accounts')
    # ### end Alembic commands ###
