"""market: timestamps + ui fields

Revision ID: 1013ffabe49a
Revises: 44f2710bfd30
Create Date: 2025-09-13 20:05:24.194426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1013ffabe49a'
down_revision: Union[str, Sequence[str], None] = '44f2710bfd30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.add_column('markets', sa.Column('category', sa.String(length=64), nullable=True))
    op.add_column('markets', sa.Column('close_at', sa.DateTime(), nullable=True))
    op.add_column('markets', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'updated_at')
    op.drop_column('markets', 'close_at')
    op.drop_column('markets', 'category')
    op.drop_column('markets', 'image_url')
    # ### end Alembic commands ###
