"""add stk tracking fields to wallet_deposits

Revision ID: 165cda07c8bb
Revises: a486581f569b
Create Date: 2026-02-12 21:04:32.462099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '165cda07c8bb'
down_revision: Union[str, Sequence[str], None] = 'a486581f569b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet_deposits', sa.Column('checkout_request_id', sa.String(length=64), nullable=True))
    op.add_column('wallet_deposits', sa.Column('merchant_request_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_wallet_deposits_checkout_request_id'), 'wallet_deposits', ['checkout_request_id'], unique=False)
    op.create_index(op.f('ix_wallet_deposits_merchant_request_id'), 'wallet_deposits', ['merchant_request_id'], unique=False)
    op.create_index(op.f('ix_wallet_deposits_mpesa_reference'), 'wallet_deposits', ['mpesa_reference'], unique=False)
    op.create_index(op.f('ix_wallet_deposits_status'), 'wallet_deposits', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_deposits_status'), table_name='wallet_deposits')
    op.drop_index(op.f('ix_wallet_deposits_mpesa_reference'), table_name='wallet_deposits')
    op.drop_index(op.f('ix_wallet_deposits_merchant_request_id'), table_name='wallet_deposits')
    op.drop_index(op.f('ix_wallet_deposits_checkout_request_id'), table_name='wallet_deposits')
    op.drop_column('wallet_deposits', 'merchant_request_id')
    op.drop_column('wallet_deposits', 'checkout_request_id')
    # ### end Alembic commands ###
