"""outcomes table and relationship

Revision ID: 44e152029f7a
Revises: 1013ffabe49a
Create Date: 2025-09-13 20:21:33.303022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44e152029f7a'
down_revision: Union[str, Sequence[str], None] = '1013ffabe49a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outcomes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('market_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outcomes_market_id'), 'outcomes', ['market_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcomes_market_id'), table_name='outcomes')
    op.drop_table('outcomes')
    # ### end Alembic commands ###
