"""add_index_wallet_ledger_created_at

Revision ID: 50fb3f516e3a
Revises: c06e55a16eed
Create Date: 2026-02-23 12:41:06.450148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50fb3f516e3a'
down_revision: Union[str, Sequence[str], None] = 'c06e55a16eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_wallet_ledger_entries_created_at'), 'wallet_ledger_entries', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_ledger_entries_created_at'), table_name='wallet_ledger_entries')
    # ### end Alembic commands ###
