"""add_fee_rate_to_market_table

Revision ID: 5a636a4ca897
Revises: cb34046a7685
Create Date: 2026-02-23 11:06:40.881093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5a636a4ca897'
down_revision: Union[str, Sequence[str], None] = 'cb34046a7685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('fee_rate_bps', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_wallet_ledger_entries_created_at'), table_name='wallet_ledger_entries')
    op.alter_column('wallet_withdrawals', 'mpesa_phone',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('wallet_withdrawals', 'mpesa_phone',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_wallet_ledger_entries_created_at'), 'wallet_ledger_entries', ['created_at'], unique=False)
    op.drop_column('markets', 'fee_rate_bps')
    # ### end Alembic commands ###
