"""add market_price_history table

Revision ID: 67597e299baf
Revises: e4b34b5bf9f2
Create Date: 2025-12-02 19:56:02.604988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67597e299baf'
down_revision: Union[str, Sequence[str], None] = 'e4b34b5bf9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_price_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('market_id', sa.String(length=36), nullable=False),
    sa.Column('outcome_id', sa.String(length=36), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('total_stake_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_price_history_market_id'), 'market_price_history', ['market_id'], unique=False)
    op.create_index(op.f('ix_market_price_history_outcome_id'), 'market_price_history', ['outcome_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_price_history_outcome_id'), table_name='market_price_history')
    op.drop_index(op.f('ix_market_price_history_market_id'), table_name='market_price_history')
    op.drop_table('market_price_history')
    # ### end Alembic commands ###
