"""add mpesa_events table

Revision ID: a486581f569b
Revises: dca01aac8b74
Create Date: 2026-02-12 20:39:51.804852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a486581f569b'
down_revision: Union[str, Sequence[str], None] = 'dca01aac8b74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mpesa_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('mpesa_trans_id', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mpesa_events_mpesa_trans_id'), 'mpesa_events', ['mpesa_trans_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mpesa_events_mpesa_trans_id'), table_name='mpesa_events')
    op.drop_table('mpesa_events')
    # ### end Alembic commands ###
