"""auth

Revision ID: b8d5183b789f
Revises: 602c9535f49c
Create Date: 2025-11-12 15:27:55.743838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d5183b789f'
down_revision: Union[str, Sequence[str], None] = '602c9535f49c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('auth_provider', sa.String(length=20), server_default=sa.text("'password'"), nullable=False))
    op.add_column('user_profiles', sa.Column('google_sub', sa.String(length=255), nullable=True))
    op.add_column('user_profiles', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    op.create_unique_constraint(None, 'user_profiles', ['google_sub'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.drop_column('user_profiles', 'avatar_url')
    op.drop_column('user_profiles', 'google_sub')
    op.drop_column('user_profiles', 'auth_provider')
    # ### end Alembic commands ###
