"""add wallet_bets

Revision ID: e4b34b5bf9f2
Revises: 04bd492c090d
Create Date: 2025-11-25 22:03:43.978705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4b34b5bf9f2'
down_revision: Union[str, Sequence[str], None] = '04bd492c090d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet_bets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('market_id', sa.String(length=36), nullable=False),
    sa.Column('outcome_id', sa.String(length=36), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price_cents_at_bet', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ledger_entry_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ledger_entry_id'], ['wallet_ledger_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_bets_ledger_entry_id'), 'wallet_bets', ['ledger_entry_id'], unique=False)
    op.create_index(op.f('ix_wallet_bets_market_id'), 'wallet_bets', ['market_id'], unique=False)
    op.create_index(op.f('ix_wallet_bets_outcome_id'), 'wallet_bets', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_wallet_bets_user_id'), 'wallet_bets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_bets_user_id'), table_name='wallet_bets')
    op.drop_index(op.f('ix_wallet_bets_outcome_id'), table_name='wallet_bets')
    op.drop_index(op.f('ix_wallet_bets_market_id'), table_name='wallet_bets')
    op.drop_index(op.f('ix_wallet_bets_ledger_entry_id'), table_name='wallet_bets')
    op.drop_table('wallet_bets')
    # ### end Alembic commands ###
